hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: data/raw/example.csv
  interim: data/interim/example.csv
  processed: data/processed/example.csv